// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Face list object.
 */
@Fluent
public final class FaceList extends MetaDataContract {
    /*
     * FaceListId of the target face list.
     */
    @JsonProperty(value = "faceListId", required = true)
    private String faceListId;

    /*
     * Persisted faces within the face list.
     */
    @JsonProperty(value = "persistedFaces")
    private List<PersistedFace> persistedFaces;

    /**
     * Get the faceListId property: FaceListId of the target face list.
     *
     * @return the faceListId value.
     */
    public String getFaceListId() {
        return this.faceListId;
    }

    /**
     * Set the faceListId property: FaceListId of the target face list.
     *
     * @param faceListId the faceListId value to set.
     * @return the FaceList object itself.
     */
    public FaceList setFaceListId(String faceListId) {
        this.faceListId = faceListId;
        return this;
    }

    /**
     * Get the persistedFaces property: Persisted faces within the face list.
     *
     * @return the persistedFaces value.
     */
    public List<PersistedFace> getPersistedFaces() {
        return this.persistedFaces;
    }

    /**
     * Set the persistedFaces property: Persisted faces within the face list.
     *
     * @param persistedFaces the persistedFaces value to set.
     * @return the FaceList object itself.
     */
    public FaceList setPersistedFaces(List<PersistedFace> persistedFaces) {
        this.persistedFaces = persistedFaces;
        return this;
    }
}
