// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Large face list object.
 */
@Fluent
public final class LargeFaceList extends MetaDataContract {
    /*
     * LargeFaceListId of the target large face list.
     */
    @JsonProperty(value = "largeFaceListId", required = true)
    private String largeFaceListId;

    /**
     * Get the largeFaceListId property: LargeFaceListId of the target large
     * face list.
     *
     * @return the largeFaceListId value.
     */
    public String getLargeFaceListId() {
        return this.largeFaceListId;
    }

    /**
     * Set the largeFaceListId property: LargeFaceListId of the target large
     * face list.
     *
     * @param largeFaceListId the largeFaceListId value to set.
     * @return the LargeFaceList object itself.
     */
    public LargeFaceList setLargeFaceListId(String largeFaceListId) {
        this.largeFaceListId = largeFaceListId;
        return this;
    }
}
