// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Properties describing present makeups on a given face.
 */
@Fluent
public final class Makeup {
    /*
     * A boolean value describing whether eye makeup is present on a face.
     */
    @JsonProperty(value = "eyeMakeup")
    private boolean eyeMakeup;

    /*
     * A boolean value describing whether lip makeup is present on a face.
     */
    @JsonProperty(value = "lipMakeup")
    private boolean lipMakeup;

    /**
     * Get the eyeMakeup property: A boolean value describing whether eye
     * makeup is present on a face.
     *
     * @return the eyeMakeup value.
     */
    public boolean isEyeMakeup() {
        return this.eyeMakeup;
    }

    /**
     * Set the eyeMakeup property: A boolean value describing whether eye
     * makeup is present on a face.
     *
     * @param eyeMakeup the eyeMakeup value to set.
     * @return the Makeup object itself.
     */
    public Makeup setEyeMakeup(boolean eyeMakeup) {
        this.eyeMakeup = eyeMakeup;
        return this;
    }

    /**
     * Get the lipMakeup property: A boolean value describing whether lip
     * makeup is present on a face.
     *
     * @return the lipMakeup value.
     */
    public boolean isLipMakeup() {
        return this.lipMakeup;
    }

    /**
     * Set the lipMakeup property: A boolean value describing whether lip
     * makeup is present on a face.
     *
     * @param lipMakeup the lipMakeup value to set.
     * @return the Makeup object itself.
     */
    public Makeup setLipMakeup(boolean lipMakeup) {
        this.lipMakeup = lipMakeup;
        return this;
    }
}
