// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Person group object.
 */
@Fluent
public final class PersonGroup extends MetaDataContract {
    /*
     * PersonGroupId of the target person group.
     */
    @JsonProperty(value = "personGroupId", required = true)
    private String personGroupId;

    /**
     * Get the personGroupId property: PersonGroupId of the target person
     * group.
     *
     * @return the personGroupId value.
     */
    public String getPersonGroupId() {
        return this.personGroupId;
    }

    /**
     * Set the personGroupId property: PersonGroupId of the target person
     * group.
     *
     * @param personGroupId the personGroupId value to set.
     * @return the PersonGroup object itself.
     */
    public PersonGroup setPersonGroupId(String personGroupId) {
        this.personGroupId = personGroupId;
        return this;
    }
}
