// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;

/**
 * Request body for updating a snapshot, with a combination of user defined
 * apply scope and user specified data.
 */
@Fluent
public final class UpdateSnapshotRequest {
    /*
     * Array of the target Face subscription ids for the snapshot, specified by
     * the user who created the snapshot when calling Snapshot - Take. For each
     * snapshot, only subscriptions included in the applyScope of Snapshot -
     * Take can apply it.
     */
    @JsonProperty(value = "applyScope")
    private List<UUID> applyScope;

    /*
     * User specified data about the snapshot for any purpose. Length should
     * not exceed 16KB.
     */
    @JsonProperty(value = "userData")
    private String userData;

    /**
     * Get the applyScope property: Array of the target Face subscription ids
     * for the snapshot, specified by the user who created the snapshot when
     * calling Snapshot - Take. For each snapshot, only subscriptions included
     * in the applyScope of Snapshot - Take can apply it.
     *
     * @return the applyScope value.
     */
    public List<UUID> getApplyScope() {
        return this.applyScope;
    }

    /**
     * Set the applyScope property: Array of the target Face subscription ids
     * for the snapshot, specified by the user who created the snapshot when
     * calling Snapshot - Take. For each snapshot, only subscriptions included
     * in the applyScope of Snapshot - Take can apply it.
     *
     * @param applyScope the applyScope value to set.
     * @return the UpdateSnapshotRequest object itself.
     */
    public UpdateSnapshotRequest setApplyScope(List<UUID> applyScope) {
        this.applyScope = applyScope;
        return this;
    }

    /**
     * Get the userData property: User specified data about the snapshot for
     * any purpose. Length should not exceed 16KB.
     *
     * @return the userData value.
     */
    public String getUserData() {
        return this.userData;
    }

    /**
     * Set the userData property: User specified data about the snapshot for
     * any purpose. Length should not exceed 16KB.
     *
     * @param userData the userData value to set.
     * @return the UpdateSnapshotRequest object itself.
     */
    public UpdateSnapshotRequest setUserData(String userData) {
        this.userData = userData;
        return this;
    }
}
