// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.face.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request to update face data.
 */
@Fluent
public final class UpdateFaceRequest {
    /*
     * User-provided data attached to the face. The size limit is 1KB.
     */
    @JsonProperty(value = "userData")
    private String userData;

    /**
     * Get the userData property: User-provided data attached to the face. The
     * size limit is 1KB.
     *
     * @return the userData value.
     */
    public String getUserData() {
        return this.userData;
    }

    /**
     * Set the userData property: User-provided data attached to the face. The
     * size limit is 1KB.
     *
     * @param userData the userData value to set.
     * @return the UpdateFaceRequest object itself.
     */
    public UpdateFaceRequest setUserData(String userData) {
        this.userData = userData;
        return this;
    }
}
