/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.vision.faceapi;

import com.microsoft.azure.cognitiveservices.vision.faceapi.models.TakeOptionalParameter;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.ListSnapshotsOptionalParameter;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.UpdateSnapshotsOptionalParameter;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.ApplyOptionalParameter;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.APIErrorException;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.OperationStatus;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.Snapshot;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.SnapshotApplyHeaders;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.SnapshotApplyMode;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.SnapshotObjectType;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.SnapshotTakeHeaders;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import com.microsoft.rest.ServiceResponseWithHeaders;
import java.io.IOException;
import java.util.List;
import java.util.UUID;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in Snapshots.
 */
public interface Snapshots {
    /**
     * Submit an operation to take a snapshot of face list, large face list, person group or large person group,
     *   with user-specified snapshot type, source object id, apply scope and an optional user
     *   data.&lt;br /&gt;
     *   The snapshot interfaces are for users to backup and restore their face data from one face subscription to
     *   another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot -
     *   Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste
     *   the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure
     *   instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     *   Taking snapshot is an asynchronous operation. An operation id can be obtained from the "Operation-Location"
     *   field in response header, to be used in OperationStatus - Get for tracking the progress of creating the
     *   snapshot. The snapshot id will be included in the "resourceLocation" field in OperationStatus - Get response
     *   when the operation status is "succeeded".&lt;br /&gt;
     *   Snapshot taking time depends on the number of person and face entries in the source object. It could be in
     *   seconds, or up to several hours for 1,000,000 persons with multiple
     *   faces.&lt;br /&gt;
     *   Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. User
     *   can delete the snapshot using Snapshot - Delete by themselves any time before
     *   expiration.&lt;br /&gt;
     *   Taking snapshot for a certain object will not block any other operations against the object. All read-only
     *   operations (Get/List and Identify/FindSimilar/Verify) can be conducted as usual. For all writable
     *   operations, including Add/Update/Delete the source object or its persons/faces and Train, they are not
     *   blocked but not recommended because writable updates may not be reflected on the snapshot during its taking.
     *   After snapshot taking is completed, all readable and writable operations can work as normal. Snapshot will
     *   also include the training results of the source object, which means target subscription the snapshot applied
     *   to does not need re-train the target object before calling
     *   Identify/FindSimilar.&lt;br /&gt;
     *   * Free-tier subscription quota: 100 take operations per month.
     *   * S0-tier subscription quota: 100 take operations per day.
     *
     * @param type User specified type for the source object to take snapshot from. Currently FaceList, PersonGroup,
     *   LargeFaceList and LargePersonGroup are supported. Possible values include: 'FaceList', 'LargeFaceList',
     *   'LargePersonGroup', 'PersonGroup'.
     * @param objectId User specified source object id to take snapshot from.
     * @param applyScope User specified array of target Face subscription ids for the snapshot. For each snapshot, only subscriptions
     *   included in the applyScope of Snapshot - Take can apply it.
     * @param takeOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void take(SnapshotObjectType type, String objectId, List<UUID> applyScope, TakeOptionalParameter takeOptionalParameter);

    /**
     * Submit an operation to take a snapshot of face list, large face list, person group or large person group,
     *   with user-specified snapshot type, source object id, apply scope and an optional user
     *   data.&lt;br /&gt;
     *   The snapshot interfaces are for users to backup and restore their face data from one face subscription to
     *   another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot -
     *   Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste
     *   the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure
     *   instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     *   Taking snapshot is an asynchronous operation. An operation id can be obtained from the "Operation-Location"
     *   field in response header, to be used in OperationStatus - Get for tracking the progress of creating the
     *   snapshot. The snapshot id will be included in the "resourceLocation" field in OperationStatus - Get response
     *   when the operation status is "succeeded".&lt;br /&gt;
     *   Snapshot taking time depends on the number of person and face entries in the source object. It could be in
     *   seconds, or up to several hours for 1,000,000 persons with multiple
     *   faces.&lt;br /&gt;
     *   Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. User
     *   can delete the snapshot using Snapshot - Delete by themselves any time before
     *   expiration.&lt;br /&gt;
     *   Taking snapshot for a certain object will not block any other operations against the object. All read-only
     *   operations (Get/List and Identify/FindSimilar/Verify) can be conducted as usual. For all writable
     *   operations, including Add/Update/Delete the source object or its persons/faces and Train, they are not
     *   blocked but not recommended because writable updates may not be reflected on the snapshot during its taking.
     *   After snapshot taking is completed, all readable and writable operations can work as normal. Snapshot will
     *   also include the training results of the source object, which means target subscription the snapshot applied
     *   to does not need re-train the target object before calling
     *   Identify/FindSimilar.&lt;br /&gt;
     *   * Free-tier subscription quota: 100 take operations per month.
     *   * S0-tier subscription quota: 100 take operations per day.
     *
     * @param type User specified type for the source object to take snapshot from. Currently FaceList, PersonGroup,
     *   LargeFaceList and LargePersonGroup are supported. Possible values include: 'FaceList', 'LargeFaceList',
     *   'LargePersonGroup', 'PersonGroup'.
     * @param objectId User specified source object id to take snapshot from.
     * @param applyScope User specified array of target Face subscription ids for the snapshot. For each snapshot, only subscriptions
     *   included in the applyScope of Snapshot - Take can apply it.
     * @param takeOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return a representation of the deferred computation of this call if successful.
     */
    Observable<Void> takeAsync(SnapshotObjectType type, String objectId, List<UUID> applyScope, TakeOptionalParameter takeOptionalParameter);


    /**
     * Submit an operation to take a snapshot of face list, large face list, person group or large person group, with user-specified snapshot type, source object id, apply scope and an optional user data.&lt;br /&gt;
     The snapshot interfaces are for users to backup and restore their face data from one face subscription to another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot - Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     Taking snapshot is an asynchronous operation. An operation id can be obtained from the "Operation-Location" field in response header, to be used in OperationStatus - Get for tracking the progress of creating the snapshot. The snapshot id will be included in the "resourceLocation" field in OperationStatus - Get response when the operation status is "succeeded".&lt;br /&gt;
     Snapshot taking time depends on the number of person and face entries in the source object. It could be in seconds, or up to several hours for 1,000,000 persons with multiple faces.&lt;br /&gt;
     Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. User can delete the snapshot using Snapshot - Delete by themselves any time before expiration.&lt;br /&gt;
     Taking snapshot for a certain object will not block any other operations against the object. All read-only operations (Get/List and Identify/FindSimilar/Verify) can be conducted as usual. For all writable operations, including Add/Update/Delete the source object or its persons/faces and Train, they are not blocked but not recommended because writable updates may not be reflected on the snapshot during its taking. After snapshot taking is completed, all readable and writable operations can work as normal. Snapshot will also include the training results of the source object, which means target subscription the snapshot applied to does not need re-train the target object before calling Identify/FindSimilar.&lt;br /&gt;
     * Free-tier subscription quota: 100 take operations per month.
     * S0-tier subscription quota: 100 take operations per day.
     *
     * @param type User specified type for the source object to take snapshot from. Currently FaceList, PersonGroup, LargeFaceList and LargePersonGroup are supported. Possible values include: 'FaceList', 'LargeFaceList', 'LargePersonGroup', 'PersonGroup'
     * @param objectId User specified source object id to take snapshot from.
     * @param applyScope User specified array of target Face subscription ids for the snapshot. For each snapshot, only subscriptions included in the applyScope of Snapshot - Take can apply it.
     * @param takeOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponseWithHeaders} object if successful.
     */
    Observable<ServiceResponseWithHeaders<Void, SnapshotTakeHeaders>> takeWithServiceResponseAsync(SnapshotObjectType type, String objectId, List<UUID> applyScope, TakeOptionalParameter takeOptionalParameter);

    /**
     * List all accessible snapshots with related information, including snapshots that were taken by the user, or
     *   snapshots to be applied to the user (subscription id was included in the applyScope in Snapshot - Take).
     *
     * @param listOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the List&lt;Snapshot&gt; object if successful.
     */
    List<Snapshot> list(ListSnapshotsOptionalParameter listOptionalParameter);

    /**
     * List all accessible snapshots with related information, including snapshots that were taken by the user, or
     *   snapshots to be applied to the user (subscription id was included in the applyScope in Snapshot - Take).
     *
     * @param listOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Snapshot&gt; object
     */
    Observable<List<Snapshot>> listAsync(ListSnapshotsOptionalParameter listOptionalParameter);


    /**
     * List all accessible snapshots with related information, including snapshots that were taken by the user, or snapshots to be applied to the user (subscription id was included in the applyScope in Snapshot - Take).
     *
     * @param listOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Snapshot&gt; object
     */
    Observable<ServiceResponse<List<Snapshot>>> listWithServiceResponseAsync(ListSnapshotsOptionalParameter listOptionalParameter);


    /**
     * Retrieve information about a snapshot. Snapshot is only accessible to the source subscription who
      *  took it, and target subscriptions included in the applyScope in Snapshot - Take.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Snapshot object if successful.
     */
    Snapshot get(UUID snapshotId);

    /**
     * Retrieve information about a snapshot. Snapshot is only accessible to the source subscription who
      *  took it, and target subscriptions included in the applyScope in Snapshot - Take.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses. * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Snapshot> getAsync(UUID snapshotId, final ServiceCallback<Snapshot> serviceCallback);

    /**
     * Retrieve information about a snapshot. Snapshot is only accessible to the source subscription who
      *  took it, and target subscriptions included in the applyScope in Snapshot - Take.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Snapshot object
     */
    Observable<Snapshot> getAsync(UUID snapshotId);

    /**
     * Retrieve information about a snapshot. Snapshot is only accessible to the source subscription who
      *  took it, and target subscriptions included in the applyScope in Snapshot - Take.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Snapshot object
     */
    Observable<ServiceResponse<Snapshot>> getWithServiceResponseAsync(UUID snapshotId);

    /**
     * Update the information of a snapshot. Only the source subscription who took the snapshot can update the
     *   snapshot.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param updateOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void update(UUID snapshotId, UpdateSnapshotsOptionalParameter updateOptionalParameter);

    /**
     * Update the information of a snapshot. Only the source subscription who took the snapshot can update the
     *   snapshot.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param updateOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return a representation of the deferred computation of this call if successful.
     */
    Observable<Void> updateAsync(UUID snapshotId, UpdateSnapshotsOptionalParameter updateOptionalParameter);


    /**
     * Update the information of a snapshot. Only the source subscription who took the snapshot can update the snapshot.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param updateOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<ServiceResponse<Void>> updateWithServiceResponseAsync(UUID snapshotId, UpdateSnapshotsOptionalParameter updateOptionalParameter);


    /**
     * Delete an existing snapshot according to the snapshotId. All object data and information in the
      *  snapshot will also be deleted. Only the source subscription who took the snapshot can delete the
      *  snapshot. If the user does not delete a snapshot with this API, the snapshot will still be
      *  automatically deleted in 48 hours after creation.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void delete(UUID snapshotId);

    /**
     * Delete an existing snapshot according to the snapshotId. All object data and information in the
      *  snapshot will also be deleted. Only the source subscription who took the snapshot can delete the
      *  snapshot. If the user does not delete a snapshot with this API, the snapshot will still be
      *  automatically deleted in 48 hours after creation.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses. * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Void> deleteAsync(UUID snapshotId, final ServiceCallback<Void> serviceCallback);

    /**
     * Delete an existing snapshot according to the snapshotId. All object data and information in the
      *  snapshot will also be deleted. Only the source subscription who took the snapshot can delete the
      *  snapshot. If the user does not delete a snapshot with this API, the snapshot will still be
      *  automatically deleted in 48 hours after creation.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return a representation of the deferred computation of this call if successful.
     */
    Observable<Void> deleteAsync(UUID snapshotId);

    /**
     * Delete an existing snapshot according to the snapshotId. All object data and information in the
      *  snapshot will also be deleted. Only the source subscription who took the snapshot can delete the
      *  snapshot. If the user does not delete a snapshot with this API, the snapshot will still be
      *  automatically deleted in 48 hours after creation.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return a representation of the deferred computation of this call if successful..
     */
    Observable<ServiceResponse<Void>> deleteWithServiceResponseAsync(UUID snapshotId);

    /**
     * Submit an operation to apply a snapshot to current subscription. For each snapshot, only subscriptions
     *   included in the applyScope of Snapshot - Take can apply it.&lt;br /&gt;
     *   The snapshot interfaces are for users to backup and restore their face data from one face subscription to
     *   another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot -
     *   Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste
     *   the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure
     *   instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     *   Applying snapshot is an asynchronous operation. An operation id can be obtained from the
     *   "Operation-Location" field in response header, to be used in OperationStatus - Get for tracking the progress
     *   of applying the snapshot. The target object id will be included in the "resourceLocation" field in
     *   OperationStatus - Get response when the operation status is "succeeded".&lt;br /&gt;
     *   Snapshot applying time depends on the number of person and face entries in the snapshot object. It could be
     *   in seconds, or up to 1 hour for 1,000,000 persons with multiple faces.&lt;br /&gt;
     *   Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. So
     *   the target subscription is required to apply the snapshot in 48 hours since its
     *   creation.&lt;br /&gt;
     *   Applying a snapshot will not block any other operations against the target object, however it is not
     *   recommended because the correctness cannot be guaranteed during snapshot applying. After snapshot applying
     *   is completed, all operations towards the target object can work as normal. Snapshot also includes the
     *   training results of the source object, which means target subscription the snapshot applied to does not need
     *   re-train the target object before calling Identify/FindSimilar.&lt;br /&gt;
     *   One snapshot can be applied multiple times in parallel, while currently only CreateNew apply mode is
     *   supported, which means the apply operation will fail if target subscription already contains an object of
     *   same type and using the same objectId. Users can specify the "objectId" in request body to avoid such
     *   conflicts.&lt;br /&gt;
     *   * Free-tier subscription quota: 100 apply operations per month.
     *   * S0-tier subscription quota: 100 apply operations per day.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param objectId User specified target object id to be created from the snapshot.
     * @param applyOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void apply(UUID snapshotId, String objectId, ApplyOptionalParameter applyOptionalParameter);

    /**
     * Submit an operation to apply a snapshot to current subscription. For each snapshot, only subscriptions
     *   included in the applyScope of Snapshot - Take can apply it.&lt;br /&gt;
     *   The snapshot interfaces are for users to backup and restore their face data from one face subscription to
     *   another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot -
     *   Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste
     *   the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure
     *   instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     *   Applying snapshot is an asynchronous operation. An operation id can be obtained from the
     *   "Operation-Location" field in response header, to be used in OperationStatus - Get for tracking the progress
     *   of applying the snapshot. The target object id will be included in the "resourceLocation" field in
     *   OperationStatus - Get response when the operation status is "succeeded".&lt;br /&gt;
     *   Snapshot applying time depends on the number of person and face entries in the snapshot object. It could be
     *   in seconds, or up to 1 hour for 1,000,000 persons with multiple faces.&lt;br /&gt;
     *   Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. So
     *   the target subscription is required to apply the snapshot in 48 hours since its
     *   creation.&lt;br /&gt;
     *   Applying a snapshot will not block any other operations against the target object, however it is not
     *   recommended because the correctness cannot be guaranteed during snapshot applying. After snapshot applying
     *   is completed, all operations towards the target object can work as normal. Snapshot also includes the
     *   training results of the source object, which means target subscription the snapshot applied to does not need
     *   re-train the target object before calling Identify/FindSimilar.&lt;br /&gt;
     *   One snapshot can be applied multiple times in parallel, while currently only CreateNew apply mode is
     *   supported, which means the apply operation will fail if target subscription already contains an object of
     *   same type and using the same objectId. Users can specify the "objectId" in request body to avoid such
     *   conflicts.&lt;br /&gt;
     *   * Free-tier subscription quota: 100 apply operations per month.
     *   * S0-tier subscription quota: 100 apply operations per day.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param objectId User specified target object id to be created from the snapshot.
     * @param applyOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return a representation of the deferred computation of this call if successful.
     */
    Observable<Void> applyAsync(UUID snapshotId, String objectId, ApplyOptionalParameter applyOptionalParameter);


    /**
     * Submit an operation to apply a snapshot to current subscription. For each snapshot, only subscriptions included in the applyScope of Snapshot - Take can apply it.&lt;br /&gt;
     The snapshot interfaces are for users to backup and restore their face data from one face subscription to another, inside same region or across regions. The workflow contains two phases, user first calls Snapshot - Take to create a copy of the source object and store it as a snapshot, then calls Snapshot - Apply to paste the snapshot to target subscription. The snapshots are stored in a centralized location (per Azure instance), so that they can be applied cross accounts and regions.&lt;br /&gt;
     Applying snapshot is an asynchronous operation. An operation id can be obtained from the "Operation-Location" field in response header, to be used in OperationStatus - Get for tracking the progress of applying the snapshot. The target object id will be included in the "resourceLocation" field in OperationStatus - Get response when the operation status is "succeeded".&lt;br /&gt;
     Snapshot applying time depends on the number of person and face entries in the snapshot object. It could be in seconds, or up to 1 hour for 1,000,000 persons with multiple faces.&lt;br /&gt;
     Snapshots will be automatically expired and cleaned in 48 hours after it is created by Snapshot - Take. So the target subscription is required to apply the snapshot in 48 hours since its creation.&lt;br /&gt;
     Applying a snapshot will not block any other operations against the target object, however it is not recommended because the correctness cannot be guaranteed during snapshot applying. After snapshot applying is completed, all operations towards the target object can work as normal. Snapshot also includes the training results of the source object, which means target subscription the snapshot applied to does not need re-train the target object before calling Identify/FindSimilar.&lt;br /&gt;
     One snapshot can be applied multiple times in parallel, while currently only CreateNew apply mode is supported, which means the apply operation will fail if target subscription already contains an object of same type and using the same objectId. Users can specify the "objectId" in request body to avoid such conflicts.&lt;br /&gt;
     * Free-tier subscription quota: 100 apply operations per month.
     * S0-tier subscription quota: 100 apply operations per day.
     *
     * @param snapshotId Id referencing a particular snapshot.
     * @param objectId User specified target object id to be created from the snapshot.
     * @param applyOptionalParameter the object representing the optional parameters to be set before calling this API
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponseWithHeaders} object if successful.
     */
    Observable<ServiceResponseWithHeaders<Void, SnapshotApplyHeaders>> applyWithServiceResponseAsync(UUID snapshotId, String objectId, ApplyOptionalParameter applyOptionalParameter);


    /**
     * Retrieve the status of a take/apply snapshot operation.
     *
     * @param operationId Id referencing a particular take/apply snapshot operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws APIErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the OperationStatus object if successful.
     */
    OperationStatus getOperationStatus(UUID operationId);

    /**
     * Retrieve the status of a take/apply snapshot operation.
     *
     * @param operationId Id referencing a particular take/apply snapshot operation.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses. * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<OperationStatus> getOperationStatusAsync(UUID operationId, final ServiceCallback<OperationStatus> serviceCallback);

    /**
     * Retrieve the status of a take/apply snapshot operation.
     *
     * @param operationId Id referencing a particular take/apply snapshot operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the OperationStatus object
     */
    Observable<OperationStatus> getOperationStatusAsync(UUID operationId);

    /**
     * Retrieve the status of a take/apply snapshot operation.
     *
     * @param operationId Id referencing a particular take/apply snapshot operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the OperationStatus object
     */
    Observable<ServiceResponse<OperationStatus>> getOperationStatusWithServiceResponseAsync(UUID operationId);

}
