// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A bounding box for an area inside an image.
 */
@Fluent
public final class BoundingRect {
    /*
     * X-coordinate of the top left point of the area, in pixels.
     */
    @JsonProperty(value = "x")
    private int x;

    /*
     * Y-coordinate of the top left point of the area, in pixels.
     */
    @JsonProperty(value = "y")
    private int y;

    /*
     * Width measured from the top-left point of the area, in pixels.
     */
    @JsonProperty(value = "w")
    private int w;

    /*
     * Height measured from the top-left point of the area, in pixels.
     */
    @JsonProperty(value = "h")
    private int h;

    /**
     * Get the x property: X-coordinate of the top left point of the area, in
     * pixels.
     *
     * @return the x value.
     */
    public int getX() {
        return this.x;
    }

    /**
     * Set the x property: X-coordinate of the top left point of the area, in
     * pixels.
     *
     * @param x the x value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setX(int x) {
        this.x = x;
        return this;
    }

    /**
     * Get the y property: Y-coordinate of the top left point of the area, in
     * pixels.
     *
     * @return the y value.
     */
    public int getY() {
        return this.y;
    }

    /**
     * Set the y property: Y-coordinate of the top left point of the area, in
     * pixels.
     *
     * @param y the y value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setY(int y) {
        this.y = y;
        return this;
    }

    /**
     * Get the w property: Width measured from the top-left point of the area,
     * in pixels.
     *
     * @return the w value.
     */
    public int getW() {
        return this.w;
    }

    /**
     * Set the w property: Width measured from the top-left point of the area,
     * in pixels.
     *
     * @param w the w value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setW(int w) {
        this.w = w;
        return this;
    }

    /**
     * Get the h property: Height measured from the top-left point of the area,
     * in pixels.
     *
     * @return the h value.
     */
    public int getH() {
        return this.h;
    }

    /**
     * Set the h property: Height measured from the top-left point of the area,
     * in pixels.
     *
     * @param h the h value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setH(int h) {
        this.h = h;
        return this;
    }
}
