// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Result of domain-specific classifications for the domain of celebrities.
 */
@Fluent
public final class CelebrityResults {
    /*
     * List of celebrities recognized in the image.
     */
    @JsonProperty(value = "celebrities")
    private List<CelebritiesModel> celebrities;

    /*
     * Id of the REST API request.
     */
    @JsonProperty(value = "requestId")
    private String requestId;

    /*
     * The metadata property.
     */
    @JsonProperty(value = "metadata")
    private ImageMetadata metadata;

    /**
     * Get the celebrities property: List of celebrities recognized in the
     * image.
     *
     * @return the celebrities value.
     */
    public List<CelebritiesModel> getCelebrities() {
        return this.celebrities;
    }

    /**
     * Set the celebrities property: List of celebrities recognized in the
     * image.
     *
     * @param celebrities the celebrities value to set.
     * @return the CelebrityResults object itself.
     */
    public CelebrityResults setCelebrities(List<CelebritiesModel> celebrities) {
        this.celebrities = celebrities;
        return this;
    }

    /**
     * Get the requestId property: Id of the REST API request.
     *
     * @return the requestId value.
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Set the requestId property: Id of the REST API request.
     *
     * @param requestId the requestId value to set.
     * @return the CelebrityResults object itself.
     */
    public CelebrityResults setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the metadata property: The metadata property.
     *
     * @return the metadata value.
     */
    public ImageMetadata getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: The metadata property.
     *
     * @param metadata the metadata value to set.
     * @return the CelebrityResults object itself.
     */
    public CelebrityResults setMetadata(ImageMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
}
