// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An object describing possible celebrity identification.
 */
@Fluent
public final class CelebritiesModel {
    /*
     * Name of the celebrity.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * Confidence level for the celebrity recognition as a value ranging from 0
     * to 1.
     */
    @JsonProperty(value = "confidence")
    private double confidence;

    /*
     * Location of the identified face in the image.
     */
    @JsonProperty(value = "faceRectangle")
    private FaceRectangle faceRectangle;

    /**
     * Get the name property: Name of the celebrity.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Name of the celebrity.
     *
     * @param name the name value to set.
     * @return the CelebritiesModel object itself.
     */
    public CelebritiesModel setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the confidence property: Confidence level for the celebrity
     * recognition as a value ranging from 0 to 1.
     *
     * @return the confidence value.
     */
    public double getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence level for the celebrity
     * recognition as a value ranging from 0 to 1.
     *
     * @param confidence the confidence value to set.
     * @return the CelebritiesModel object itself.
     */
    public CelebritiesModel setConfidence(double confidence) {
        this.confidence = confidence;
        return this;
    }

    /**
     * Get the faceRectangle property: Location of the identified face in the
     * image.
     *
     * @return the faceRectangle value.
     */
    public FaceRectangle getFaceRectangle() {
        return this.faceRectangle;
    }

    /**
     * Set the faceRectangle property: Location of the identified face in the
     * image.
     *
     * @param faceRectangle the faceRectangle value to set.
     * @return the CelebritiesModel object itself.
     */
    public CelebritiesModel setFaceRectangle(FaceRectangle faceRectangle) {
        this.faceRectangle = faceRectangle;
        return this;
    }
}
