// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.JsonFlatten;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
 */
@JsonFlatten
@Fluent
public class ImageDescription {
    /*
     * A collection of image tags.
     */
    @JsonProperty(value = "description.tags")
    private List<String> tags;

    /*
     * A list of captions, sorted by confidence level.
     */
    @JsonProperty(value = "description.captions")
    private List<ImageCaption> captions;

    /*
     * Id of the REST API request.
     */
    @JsonProperty(value = "requestId")
    private String requestId;

    /*
     * The metadata property.
     */
    @JsonProperty(value = "metadata")
    private ImageMetadata metadata;

    /**
     * Get the tags property: A collection of image tags.
     *
     * @return the tags value.
     */
    public List<String> getTags() {
        return this.tags;
    }

    /**
     * Set the tags property: A collection of image tags.
     *
     * @param tags the tags value to set.
     * @return the ImageDescription object itself.
     */
    public ImageDescription setTags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the captions property: A list of captions, sorted by confidence
     * level.
     *
     * @return the captions value.
     */
    public List<ImageCaption> getCaptions() {
        return this.captions;
    }

    /**
     * Set the captions property: A list of captions, sorted by confidence
     * level.
     *
     * @param captions the captions value to set.
     * @return the ImageDescription object itself.
     */
    public ImageDescription setCaptions(List<ImageCaption> captions) {
        this.captions = captions;
        return this;
    }

    /**
     * Get the requestId property: Id of the REST API request.
     *
     * @return the requestId value.
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Set the requestId property: Id of the REST API request.
     *
     * @param requestId the requestId value to set.
     * @return the ImageDescription object itself.
     */
    public ImageDescription setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the metadata property: The metadata property.
     *
     * @return the metadata value.
     */
    public ImageMetadata getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: The metadata property.
     *
     * @param metadata the metadata value to set.
     * @return the ImageDescription object itself.
     */
    public ImageDescription setMetadata(ImageMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
}
