// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An image caption, i.e. a brief description of what the image depicts.
 */
@Fluent
public final class ImageCaption {
    /*
     * The text of the caption.
     */
    @JsonProperty(value = "text")
    private String text;

    /*
     * The level of confidence the service has in the caption.
     */
    @JsonProperty(value = "confidence")
    private double confidence;

    /**
     * Get the text property: The text of the caption.
     *
     * @return the text value.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Set the text property: The text of the caption.
     *
     * @param text the text value to set.
     * @return the ImageCaption object itself.
     */
    public ImageCaption setText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the confidence property: The level of confidence the service has in
     * the caption.
     *
     * @return the confidence value.
     */
    public double getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: The level of confidence the service has in
     * the caption.
     *
     * @param confidence the confidence value to set.
     * @return the ImageCaption object itself.
     */
    public ImageCaption setConfidence(double confidence) {
        this.confidence = confidence;
        return this;
    }
}
