// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Result of domain-specific classifications for the domain of landmarks.
 */
@Fluent
public final class LandmarkResults {
    /*
     * List of landmarks recognized in the image.
     */
    @JsonProperty(value = "landmarks")
    private List<LandmarksModel> landmarks;

    /*
     * Id of the REST API request.
     */
    @JsonProperty(value = "requestId")
    private String requestId;

    /*
     * The metadata property.
     */
    @JsonProperty(value = "metadata")
    private ImageMetadata metadata;

    /**
     * Get the landmarks property: List of landmarks recognized in the image.
     *
     * @return the landmarks value.
     */
    public List<LandmarksModel> getLandmarks() {
        return this.landmarks;
    }

    /**
     * Set the landmarks property: List of landmarks recognized in the image.
     *
     * @param landmarks the landmarks value to set.
     * @return the LandmarkResults object itself.
     */
    public LandmarkResults setLandmarks(List<LandmarksModel> landmarks) {
        this.landmarks = landmarks;
        return this;
    }

    /**
     * Get the requestId property: Id of the REST API request.
     *
     * @return the requestId value.
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Set the requestId property: Id of the REST API request.
     *
     * @param requestId the requestId value to set.
     * @return the LandmarkResults object itself.
     */
    public LandmarkResults setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the metadata property: The metadata property.
     *
     * @return the metadata value.
     */
    public ImageMetadata getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: The metadata property.
     *
     * @param metadata the metadata value to set.
     * @return the LandmarkResults object itself.
     */
    public LandmarkResults setMetadata(ImageMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
}
