// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * An object representing a recognized text line.
 */
@Fluent
public final class Line {
    /*
     * Bounding box of a recognized line.
     */
    @JsonProperty(value = "boundingBox")
    private List<Double> boundingBox;

    /*
     * The text content of the line.
     */
    @JsonProperty(value = "text")
    private String text;

    /*
     * List of words in the text line.
     */
    @JsonProperty(value = "words")
    private List<Word> words;

    /**
     * Get the boundingBox property: Bounding box of a recognized line.
     *
     * @return the boundingBox value.
     */
    public List<Double> getBoundingBox() {
        return this.boundingBox;
    }

    /**
     * Set the boundingBox property: Bounding box of a recognized line.
     *
     * @param boundingBox the boundingBox value to set.
     * @return the Line object itself.
     */
    public Line setBoundingBox(List<Double> boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }

    /**
     * Get the text property: The text content of the line.
     *
     * @return the text value.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Set the text property: The text content of the line.
     *
     * @param text the text value to set.
     * @return the Line object itself.
     */
    public Line setText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the words property: List of words in the text line.
     *
     * @return the words value.
     */
    public List<Word> getWords() {
        return this.words;
    }

    /**
     * Set the words property: List of words in the text line.
     *
     * @param words the words value to set.
     * @return the Line object itself.
     */
    public Line setWords(List<Word> words) {
        this.words = words;
        return this;
    }
}
