// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Result of the List Domain Models operation.
 */
@Fluent
public final class ListModelsResult {
    /*
     * An array of supported models.
     */
    @JsonProperty(value = "models", access = JsonProperty.Access.WRITE_ONLY)
    private List<ModelDescription> modelsProperty;

    /**
     * Get the modelsProperty property: An array of supported models.
     *
     * @return the modelsProperty value.
     */
    public List<ModelDescription> getModelsProperty() {
        return this.modelsProperty;
    }
}
