// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * OCR result of the read operation.
 */
@Fluent
public final class ReadOperationResult {
    /*
     * Status of the read operation. Possible values include: 'NotStarted',
     * 'Running', 'Failed', 'Succeeded'
     */
    @JsonProperty(value = "status")
    private TextOperationStatusCodes status;

    /*
     * An array of text recognition result of the read operation.
     */
    @JsonProperty(value = "recognitionResults")
    private List<TextRecognitionResult> recognitionResults;

    /**
     * Get the status property: Status of the read operation. Possible values
     * include: 'NotStarted', 'Running', 'Failed', 'Succeeded'.
     *
     * @return the status value.
     */
    public TextOperationStatusCodes getStatus() {
        return this.status;
    }

    /**
     * Set the status property: Status of the read operation. Possible values
     * include: 'NotStarted', 'Running', 'Failed', 'Succeeded'.
     *
     * @param status the status value to set.
     * @return the ReadOperationResult object itself.
     */
    public ReadOperationResult setStatus(TextOperationStatusCodes status) {
        this.status = status;
        return this;
    }

    /**
     * Get the recognitionResults property: An array of text recognition result
     * of the read operation.
     *
     * @return the recognitionResults value.
     */
    public List<TextRecognitionResult> getRecognitionResults() {
        return this.recognitionResults;
    }

    /**
     * Set the recognitionResults property: An array of text recognition result
     * of the read operation.
     *
     * @param recognitionResults the recognitionResults value to set.
     * @return the ReadOperationResult object itself.
     */
    public ReadOperationResult setRecognitionResults(List<TextRecognitionResult> recognitionResults) {
        this.recognitionResults = recognitionResults;
        return this;
    }
}
