// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.cognitiveservices.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * An object representing a recognized word.
 */
@Fluent
public final class Word {
    /*
     * Bounding box of a recognized word.
     */
    @JsonProperty(value = "boundingBox", required = true)
    private List<Double> boundingBox;

    /*
     * The text content of the word.
     */
    @JsonProperty(value = "text", required = true)
    private String text;

    /*
     * Qualitative confidence measure. Possible values include: 'High', 'Low'
     */
    @JsonProperty(value = "confidence")
    private TextRecognitionResultConfidenceClass confidence;

    /**
     * Get the boundingBox property: Bounding box of a recognized word.
     *
     * @return the boundingBox value.
     */
    public List<Double> getBoundingBox() {
        return this.boundingBox;
    }

    /**
     * Set the boundingBox property: Bounding box of a recognized word.
     *
     * @param boundingBox the boundingBox value to set.
     * @return the Word object itself.
     */
    public Word setBoundingBox(List<Double> boundingBox) {
        this.boundingBox = boundingBox;
        return this;
    }

    /**
     * Get the text property: The text content of the word.
     *
     * @return the text value.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Set the text property: The text content of the word.
     *
     * @param text the text value to set.
     * @return the Word object itself.
     */
    public Word setText(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get the confidence property: Qualitative confidence measure. Possible
     * values include: 'High', 'Low'.
     *
     * @return the confidence value.
     */
    public TextRecognitionResultConfidenceClass getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Qualitative confidence measure. Possible
     * values include: 'High', 'Low'.
     *
     * @param confidence the confidence value to set.
     * @return the Word object itself.
     */
    public Word setConfidence(TextRecognitionResultConfidenceClass confidence) {
        this.confidence = confidence;
        return this;
    }
}
