// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ApplySnapshotRequest model. */
@Fluent
public final class ApplySnapshotRequest {
    /*
     * User specified target object id to be created from the snapshot.
     */
    @JsonProperty(value = "objectId", required = true)
    private String objectId;

    /*
     * Snapshot applying mode. Currently only CreateNew is supported, which
     * means the apply operation will fail if target subscription already
     * contains an object of same type and using the same objectId. Users can
     * specify the "objectId" in request body to avoid such conflicts.
     */
    @JsonProperty(value = "mode")
    private String mode;

    /** Creates an instance of ApplySnapshotRequest class. */
    public ApplySnapshotRequest() {
        mode = "CreateNew";
    }

    /**
     * Get the objectId property: User specified target object id to be created from the snapshot.
     *
     * @return the objectId value.
     */
    public String getObjectId() {
        return this.objectId;
    }

    /**
     * Set the objectId property: User specified target object id to be created from the snapshot.
     *
     * @param objectId the objectId value to set.
     * @return the ApplySnapshotRequest object itself.
     */
    public ApplySnapshotRequest setObjectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the mode property: Snapshot applying mode. Currently only CreateNew is supported, which means the apply
     * operation will fail if target subscription already contains an object of same type and using the same objectId.
     * Users can specify the "objectId" in request body to avoid such conflicts.
     *
     * @return the mode value.
     */
    public String getMode() {
        return this.mode;
    }

    /**
     * Set the mode property: Snapshot applying mode. Currently only CreateNew is supported, which means the apply
     * operation will fail if target subscription already contains an object of same type and using the same objectId.
     * Users can specify the "objectId" in request body to avoid such conflicts.
     *
     * @param mode the mode value to set.
     * @return the ApplySnapshotRequest object itself.
     */
    public ApplySnapshotRequest setMode(String mode) {
        this.mode = mode;
        return this;
    }
}
