// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The Blur model. */
@Fluent
public final class Blur {
    /*
     * An enum value indicating level of blurriness.
     */
    @JsonProperty(value = "blurLevel")
    private BlurLevel blurLevel;

    /*
     * A number indicating level of blurriness ranging from 0 to 1.
     */
    @JsonProperty(value = "value")
    private Float value;

    /**
     * Get the blurLevel property: An enum value indicating level of blurriness.
     *
     * @return the blurLevel value.
     */
    public BlurLevel getBlurLevel() {
        return this.blurLevel;
    }

    /**
     * Set the blurLevel property: An enum value indicating level of blurriness.
     *
     * @param blurLevel the blurLevel value to set.
     * @return the Blur object itself.
     */
    public Blur setBlurLevel(BlurLevel blurLevel) {
        this.blurLevel = blurLevel;
        return this;
    }

    /**
     * Get the value property: A number indicating level of blurriness ranging from 0 to 1.
     *
     * @return the value value.
     */
    public Float getValue() {
        return this.value;
    }

    /**
     * Set the value property: A number indicating level of blurriness ranging from 0 to 1.
     *
     * @param value the value value to set.
     * @return the Blur object itself.
     */
    public Blur setValue(Float value) {
        this.value = value;
        return this;
    }
}
