// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The FaceRectangle model. */
@Fluent
public final class FaceRectangle {
    /*
     * The width of the rectangle, in pixels.
     */
    @JsonProperty(value = "width", required = true)
    private int width;

    /*
     * The height of the rectangle, in pixels.
     */
    @JsonProperty(value = "height", required = true)
    private int height;

    /*
     * The distance from the left edge if the image to the left edge of the
     * rectangle, in pixels.
     */
    @JsonProperty(value = "left", required = true)
    private int left;

    /*
     * The distance from the top edge if the image to the top edge of the
     * rectangle, in pixels.
     */
    @JsonProperty(value = "top", required = true)
    private int top;

    /**
     * Get the width property: The width of the rectangle, in pixels.
     *
     * @return the width value.
     */
    public int getWidth() {
        return this.width;
    }

    /**
     * Set the width property: The width of the rectangle, in pixels.
     *
     * @param width the width value to set.
     * @return the FaceRectangle object itself.
     */
    public FaceRectangle setWidth(int width) {
        this.width = width;
        return this;
    }

    /**
     * Get the height property: The height of the rectangle, in pixels.
     *
     * @return the height value.
     */
    public int getHeight() {
        return this.height;
    }

    /**
     * Set the height property: The height of the rectangle, in pixels.
     *
     * @param height the height value to set.
     * @return the FaceRectangle object itself.
     */
    public FaceRectangle setHeight(int height) {
        this.height = height;
        return this;
    }

    /**
     * Get the left property: The distance from the left edge if the image to the left edge of the rectangle, in pixels.
     *
     * @return the left value.
     */
    public int getLeft() {
        return this.left;
    }

    /**
     * Set the left property: The distance from the left edge if the image to the left edge of the rectangle, in pixels.
     *
     * @param left the left value to set.
     * @return the FaceRectangle object itself.
     */
    public FaceRectangle setLeft(int left) {
        this.left = left;
        return this;
    }

    /**
     * Get the top property: The distance from the top edge if the image to the top edge of the rectangle, in pixels.
     *
     * @return the top value.
     */
    public int getTop() {
        return this.top;
    }

    /**
     * Set the top property: The distance from the top edge if the image to the top edge of the rectangle, in pixels.
     *
     * @param top the top value to set.
     * @return the FaceRectangle object itself.
     */
    public FaceRectangle setTop(int top) {
        this.top = top;
        return this;
    }
}
