// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;

/** The GroupResult model. */
@Fluent
public final class GroupResult {
    /*
     * A partition of the original faces based on face similarity. Groups are
     * ranked by number of faces
     */
    @JsonProperty(value = "groups", required = true)
    private List<List<UUID>> groups;

    /*
     * Face ids array of faces that cannot find any similar faces from original
     * faces.
     */
    @JsonProperty(value = "messyGroup")
    private List<UUID> messyGroup;

    /**
     * Get the groups property: A partition of the original faces based on face similarity. Groups are ranked by number
     * of faces.
     *
     * @return the groups value.
     */
    public List<List<UUID>> getGroups() {
        return this.groups;
    }

    /**
     * Set the groups property: A partition of the original faces based on face similarity. Groups are ranked by number
     * of faces.
     *
     * @param groups the groups value to set.
     * @return the GroupResult object itself.
     */
    public GroupResult setGroups(List<List<UUID>> groups) {
        this.groups = groups;
        return this;
    }

    /**
     * Get the messyGroup property: Face ids array of faces that cannot find any similar faces from original faces.
     *
     * @return the messyGroup value.
     */
    public List<UUID> getMessyGroup() {
        return this.messyGroup;
    }

    /**
     * Set the messyGroup property: Face ids array of faces that cannot find any similar faces from original faces.
     *
     * @param messyGroup the messyGroup value to set.
     * @return the GroupResult object itself.
     */
    public GroupResult setMessyGroup(List<UUID> messyGroup) {
        this.messyGroup = messyGroup;
        return this;
    }
}
