// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;

/** The IdentifyCandidate model. */
@Fluent
public final class IdentifyCandidate {
    /*
     * Id of candidate
     */
    @JsonProperty(value = "personId", required = true)
    private UUID personId;

    /*
     * Confidence threshold of identification, used to judge whether one face
     * belong to one person. The range of confidenceThreshold is [0, 1]
     * (default specified by algorithm).
     */
    @JsonProperty(value = "confidence", required = true)
    private float confidence;

    /**
     * Get the personId property: Id of candidate.
     *
     * @return the personId value.
     */
    public UUID getPersonId() {
        return this.personId;
    }

    /**
     * Set the personId property: Id of candidate.
     *
     * @param personId the personId value to set.
     * @return the IdentifyCandidate object itself.
     */
    public IdentifyCandidate setPersonId(UUID personId) {
        this.personId = personId;
        return this;
    }

    /**
     * Get the confidence property: Confidence threshold of identification, used to judge whether one face belong to one
     * person. The range of confidenceThreshold is [0, 1] (default specified by algorithm).
     *
     * @return the confidence value.
     */
    public float getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence threshold of identification, used to judge whether one face belong to one
     * person. The range of confidenceThreshold is [0, 1] (default specified by algorithm).
     *
     * @param confidence the confidence value to set.
     * @return the IdentifyCandidate object itself.
     */
    public IdentifyCandidate setConfidence(float confidence) {
        this.confidence = confidence;
        return this;
    }
}
