// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The Makeup model. */
@Fluent
public final class Makeup {
    /*
     * A boolean value describing whether eye makeup is present on a face.
     */
    @JsonProperty(value = "eyeMakeup")
    private Boolean eyeMakeup;

    /*
     * A boolean value describing whether lip makeup is present on a face.
     */
    @JsonProperty(value = "lipMakeup")
    private Boolean lipMakeup;

    /**
     * Get the eyeMakeup property: A boolean value describing whether eye makeup is present on a face.
     *
     * @return the eyeMakeup value.
     */
    public Boolean isEyeMakeup() {
        return this.eyeMakeup;
    }

    /**
     * Set the eyeMakeup property: A boolean value describing whether eye makeup is present on a face.
     *
     * @param eyeMakeup the eyeMakeup value to set.
     * @return the Makeup object itself.
     */
    public Makeup setEyeMakeup(Boolean eyeMakeup) {
        this.eyeMakeup = eyeMakeup;
        return this;
    }

    /**
     * Get the lipMakeup property: A boolean value describing whether lip makeup is present on a face.
     *
     * @return the lipMakeup value.
     */
    public Boolean isLipMakeup() {
        return this.lipMakeup;
    }

    /**
     * Set the lipMakeup property: A boolean value describing whether lip makeup is present on a face.
     *
     * @param lipMakeup the lipMakeup value to set.
     * @return the Makeup object itself.
     */
    public Makeup setLipMakeup(Boolean lipMakeup) {
        this.lipMakeup = lipMakeup;
        return this;
    }
}
