// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The MetaDataContract model. */
@Fluent
public class MetaDataContract extends NameAndUserDataContract {
    /*
     * Name of recognition model. Recognition model is used when the face
     * features are extracted and associated with detected faceIds,
     * (Large)FaceList or (Large)PersonGroup. A recognition model name can be
     * provided when performing Face - Detect or (Large)FaceList - Create or
     * (Large)PersonGroup - Create. The default value is 'recognition_01', if
     * latest model needed, please explicitly specify the model you need.
     */
    @JsonProperty(value = "recognitionModel")
    private RecognitionModel recognitionModel;

    /**
     * Get the recognitionModel property: Name of recognition model. Recognition model is used when the face features
     * are extracted and associated with detected faceIds, (Large)FaceList or (Large)PersonGroup. A recognition model
     * name can be provided when performing Face - Detect or (Large)FaceList - Create or (Large)PersonGroup - Create.
     * The default value is 'recognition_01', if latest model needed, please explicitly specify the model you need.
     *
     * @return the recognitionModel value.
     */
    public RecognitionModel getRecognitionModel() {
        return this.recognitionModel;
    }

    /**
     * Set the recognitionModel property: Name of recognition model. Recognition model is used when the face features
     * are extracted and associated with detected faceIds, (Large)FaceList or (Large)PersonGroup. A recognition model
     * name can be provided when performing Face - Detect or (Large)FaceList - Create or (Large)PersonGroup - Create.
     * The default value is 'recognition_01', if latest model needed, please explicitly specify the model you need.
     *
     * @param recognitionModel the recognitionModel value to set.
     * @return the MetaDataContract object itself.
     */
    public MetaDataContract setRecognitionModel(RecognitionModel recognitionModel) {
        this.recognitionModel = recognitionModel;
        return this;
    }
}
