// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;

/** The Person model. */
@Fluent
public final class Person extends NameAndUserDataContract {
    /*
     * PersonId of the target face list.
     */
    @JsonProperty(value = "personId", required = true)
    private UUID personId;

    /*
     * PersistedFaceIds of registered faces in the person. These
     * persistedFaceIds are returned from Person - Add a Person Face, and will
     * not expire.
     */
    @JsonProperty(value = "persistedFaceIds")
    private List<UUID> persistedFaceIds;

    /**
     * Get the personId property: PersonId of the target face list.
     *
     * @return the personId value.
     */
    public UUID getPersonId() {
        return this.personId;
    }

    /**
     * Set the personId property: PersonId of the target face list.
     *
     * @param personId the personId value to set.
     * @return the Person object itself.
     */
    public Person setPersonId(UUID personId) {
        this.personId = personId;
        return this;
    }

    /**
     * Get the persistedFaceIds property: PersistedFaceIds of registered faces in the person. These persistedFaceIds are
     * returned from Person - Add a Person Face, and will not expire.
     *
     * @return the persistedFaceIds value.
     */
    public List<UUID> getPersistedFaceIds() {
        return this.persistedFaceIds;
    }

    /**
     * Set the persistedFaceIds property: PersistedFaceIds of registered faces in the person. These persistedFaceIds are
     * returned from Person - Add a Person Face, and will not expire.
     *
     * @param persistedFaceIds the persistedFaceIds value to set.
     * @return the Person object itself.
     */
    public Person setPersistedFaceIds(List<UUID> persistedFaceIds) {
        this.persistedFaceIds = persistedFaceIds;
        return this;
    }
}
