// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.faceapi.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;

/** The VerifyFaceToPersonRequest model. */
@Fluent
public final class VerifyFaceToPersonRequest {
    /*
     * FaceId of the face, comes from Face - Detect
     */
    @JsonProperty(value = "faceId", required = true)
    private UUID faceId;

    /*
     * Using existing personGroupId and personId for fast loading a specified
     * person. personGroupId is created in PersonGroup - Create. Parameter
     * personGroupId and largePersonGroupId should not be provided at the same
     * time.
     */
    @JsonProperty(value = "personGroupId")
    private String personGroupId;

    /*
     * Using existing largePersonGroupId and personId for fast loading a
     * specified person. largePersonGroupId is created in LargePersonGroup -
     * Create. Parameter personGroupId and largePersonGroupId should not be
     * provided at the same time.
     */
    @JsonProperty(value = "largePersonGroupId")
    private String largePersonGroupId;

    /*
     * Specify a certain person in a person group or a large person group.
     * personId is created in PersonGroup Person - Create or LargePersonGroup
     * Person - Create.
     */
    @JsonProperty(value = "personId", required = true)
    private UUID personId;

    /**
     * Get the faceId property: FaceId of the face, comes from Face - Detect.
     *
     * @return the faceId value.
     */
    public UUID getFaceId() {
        return this.faceId;
    }

    /**
     * Set the faceId property: FaceId of the face, comes from Face - Detect.
     *
     * @param faceId the faceId value to set.
     * @return the VerifyFaceToPersonRequest object itself.
     */
    public VerifyFaceToPersonRequest setFaceId(UUID faceId) {
        this.faceId = faceId;
        return this;
    }

    /**
     * Get the personGroupId property: Using existing personGroupId and personId for fast loading a specified person.
     * personGroupId is created in PersonGroup - Create. Parameter personGroupId and largePersonGroupId should not be
     * provided at the same time.
     *
     * @return the personGroupId value.
     */
    public String getPersonGroupId() {
        return this.personGroupId;
    }

    /**
     * Set the personGroupId property: Using existing personGroupId and personId for fast loading a specified person.
     * personGroupId is created in PersonGroup - Create. Parameter personGroupId and largePersonGroupId should not be
     * provided at the same time.
     *
     * @param personGroupId the personGroupId value to set.
     * @return the VerifyFaceToPersonRequest object itself.
     */
    public VerifyFaceToPersonRequest setPersonGroupId(String personGroupId) {
        this.personGroupId = personGroupId;
        return this;
    }

    /**
     * Get the largePersonGroupId property: Using existing largePersonGroupId and personId for fast loading a specified
     * person. largePersonGroupId is created in LargePersonGroup - Create. Parameter personGroupId and
     * largePersonGroupId should not be provided at the same time.
     *
     * @return the largePersonGroupId value.
     */
    public String getLargePersonGroupId() {
        return this.largePersonGroupId;
    }

    /**
     * Set the largePersonGroupId property: Using existing largePersonGroupId and personId for fast loading a specified
     * person. largePersonGroupId is created in LargePersonGroup - Create. Parameter personGroupId and
     * largePersonGroupId should not be provided at the same time.
     *
     * @param largePersonGroupId the largePersonGroupId value to set.
     * @return the VerifyFaceToPersonRequest object itself.
     */
    public VerifyFaceToPersonRequest setLargePersonGroupId(String largePersonGroupId) {
        this.largePersonGroupId = largePersonGroupId;
        return this;
    }

    /**
     * Get the personId property: Specify a certain person in a person group or a large person group. personId is
     * created in PersonGroup Person - Create or LargePersonGroup Person - Create.
     *
     * @return the personId value.
     */
    public UUID getPersonId() {
        return this.personId;
    }

    /**
     * Set the personId property: Specify a certain person in a person group or a large person group. personId is
     * created in PersonGroup Person - Create or LargePersonGroup Person - Create.
     *
     * @param personId the personId value to set.
     * @return the VerifyFaceToPersonRequest object itself.
     */
    public VerifyFaceToPersonRequest setPersonId(UUID personId) {
        this.personId = personId;
        return this;
    }
}
